# 빌드하기 위해서 as build 입력
FROM node:24.13.0 as build

# WORKDIR을 지정해주면, 아래 COPY 명령어로
# 현재 frontend의 파일 경로에 있는 파일들을 추후 docker run 명령어 실행시,
# 컨테이너 내부의 WORKDIR 로 복사할 수 있게 된다.
WORKDIR /app

# package.json의 아래 항목을 복사하기 위하여 선언
# ./ => 위에 선언한 /app에 복사하겠다는 뜻
# "dependencies": {
#     "react": "^19.2.0",
#     "react-dom": "^19.2.0"
#   },
COPY package.json ./

RUN npm i

# 현재위치에있는 모든 것을 app 위치에 복사
COPY . .

RUN npm run build

FROM nginx:1.28

# 어떤 형식에서는 dist를 build로 입력하는데 그 형식이 무엇인지는 까먹음... 냠냠..
# 위에서 빌드하기 위한 as의 뒤의 이름을 다음과 같이 작성 "from=build" 
COPY --from=build /app/dist /usr/share/nginx/html
COPY ./default.conf /etc/nginx/conf.d/default.conf

EXPOSE 80

# 자동으로 키기 위한 명령어
CMD ["nginx","-g","daemon off;"]

# 작성이 완료되면 아래 명령어 입력
# docker build -t react:0.1 .
# 이후 컨테이너 생성 및 실행
# docker run -d -p 80:80 --name web react:0.1