services:
  react:
    container_name: react
    image: node:24.13.0
    depends_on:
      - fastapi
    ports:
      - 80:5173
    volumes:
      - ../workspace/frontend:/workspace/frontend
    command: ["sleep", "infinity"]
  
  fastapi:
    container_name: fastapi
    image: python:3.12.9
    depends_on:
      - mariadb
    # 확인시에만 오픈 개발 할때는 미 오픈
    ports:
      - 8000:8000
    volumes:
      - ../workspace/backend:/workspace/backend
    command: ["sleep", "infinity"]

  mariadb:
    container_name: mariadb
    image: mariadb:12.1.2
    # 확인시에만 오픈 개발 할때는 미 오픈
    ports:
      - 3306:3306
    volumes:
      - ../workspace/mariadb/conf.d:/etc/mysql/conf.d:ro
      - ../workspace/mariadb/data:/var/lib/maysql:mv
      - ../workspace/mariadb/conf.d:/etc/mysql/conf.d:ro
    environment:
      - name=value