FROM python:3.13.11

RUN apt-get update
RUN apt-get upgrade -y
RUN curl -LsSf https://astral.sh/uv/install.sh | sh
RUN pip install uv

WORKDIR /workspace

COPY pyproject.toml uv.lock ./

RUN uv sync --frozen --no-dev

COPY main.py main.py

CMD ["uv", "run", "fastapi", "run", "--host", "0.0.0.0", "--port", "8000"]

# build 진행
# docker build -t backend .

# docker 실행
# docker run -d -p 8000:8000 --name fastapi backend