FROM python:3.13.11

WORKDIR /app

RUN pip install --no-cache-dir uv

COPY pyproject.toml uv.lock* ./

RUN uv sync

COPY . .

EXPOSE 8002

CMD ["uv", "run", "uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8002"]

# dockerfile은 백앤드 폴더 안에 저장하고 작성이 완료되면 아래 명령어 백앤드 폴더 터미널에서 입력 예정
# docker build -t fastapi_2:0.1 .
# 이후 컨테이너 생성 및 실행
# docker run --network=my-net -d -p 8002:8002 --name app2 fastapi_2:0.1