FROM uv:1

WORKDIR /workspace

COPY pyproject.toml uv.lock ./

RUN uv sync --frozen --no-dev

COPY main.py main.py
COPY settings.py settings.py
COPY .env .env

CMD ["uv", "run", "fastapi", "run", "--host", "0.0.0.0", "--port", "8000"]

# build 진행
# docker build -t app:1 .

# docker 실행
# docker run -d -p 8000:8000 --name app1 app:1