# fastapi는 빌드 결과물이 없기 때문에 nginx를 사용하지 않음
FROM python:3.13.11

WORKDIR /app

# uv 설치
RUN pip install --no-cache-dir uv

# 의존성 파일 복사
COPY pyproject.toml uv.lock* ./

# 의존성 설치
RUN uv sync

# 앱 코드 복사
COPY . .

# 포트를 8000으로 설정 
EXPOSE 8000

CMD ["uv", "run", "uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]

# 작성이 완료되면 아래 명령어 입력
# docker build -t fastapi:0.1 .
# 이후 컨테이너 생성 및 실행
# docker run -d -p 80:80 --name web fastapi:0.1