apiVersion: v1
kind: PersistentVolume
metadata:
  name: mariadb-pv
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 5Gi
  storageClassName: local-storage
  persistentVolumeReclaimPolicy: Retain
  local:
    path: /run/desktop/mnt/host/c/IDE/workspaces/WEB_STUDY-study/study/Y2026/02_Feb/26th/study39/mariadb/data
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - docker-desktop


# 등록하기
# kubectl create -f mariadb-pv.yaml

# 삭제하기
# kubectl delete -f mariadb-pv.yaml

# 확인하기
# kubectl get configmaps