apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mariadb-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: local-storage

# 등록하기
# kubectl create -f mariadb-pvc.yaml

# 삭제하기
# kubectl delete -f mariadb-pvc.yaml

# 확인하기
# kubectl get configmaps