apiVersion: v1
kind: Service
metadata:
  name: app1-service
spec:
  type: LoadBalancer
  ports:
  - port: 8001
    targetPort: 8000
  selector:
    app: app1

# 등록하기
# kubectl create -f app1-service.yaml

# 삭제하기
# kubectl delete -f app1-service.yaml

# 확인하기
# kubectl get services

# LoadBalancer를 이용하면 http://localhost:8000/으로 연결이 된다.