apiVersion: v1
kind: Service
metadata:
  name: app2-service
spec:
  type: ClusterIP
  ports:
  - port: 8000
    targetPort: 8000
  selector:
    app: app2

# 등록하기
# kubectl create -f app2-service.yaml

# 삭제하기
# kubectl delete -f app2-service.yaml

# 수정된 yaml 파일 적용하기
# kubectl apply -f app2-service.yaml

# 확인하기
# kubectl get services