apiVersion: v1
kind: ConfigMap

metadata:
  name: mariadb-config

data:
  MARIADB_HOST: "localhost"
  MARIADB_PORT: "3306"
  MARIADB_ROOT_PASSWORD: "1234"
  MARIADB_DATABASE: "edu"
  TZ: "Asia/seoul"
  LC_ALL: "en_US.UTF-8"

# 등록하기
# kubectl create -f mariadb-config.yaml

# 삭제하기
# kubectl delete -f mariadb-config.yaml

# 확인하기
# kubectl get configmaps