apiVersion: apps/v1
kind: Deployment
metadata:
  name: app2-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app2
  template:
    metadata:
      labels:
        app: app2
    spec:
      containers:
      - name: app2-container
        image: app:2
        ports:
        - containerPort: 8000
        env:
        - name: ROOT_PATH
          valueFrom:
            configMapKeyRef:
              name: app2-config
              key: ROOT_PATH
        - name: REDIS_HOST
          valueFrom:
            configMapKeyRef:
              name: app2-config
              key: REDIS_HOST
        - name: REDIS_PORT
          valueFrom:
            configMapKeyRef:
              name: app2-config
              key: REDIS_PORT
        - name: REDIS_ACCESS_DB
          valueFrom:
            configMapKeyRef:
              name: app2-config
              key: REDIS_ACCESS_DB
        - name: REDIS_REFRESH_DB
          valueFrom:
            configMapKeyRef:
              name: app2-config
              key: REDIS_REFRESH_DB
        - name: KAKAO_REST_API_KEY
          valueFrom:
            configMapKeyRef:
              name: app2-config
              key: KAKAO_REST_API_KEY
        - name: KAKAO_CLIENT_SECRET
          valueFrom:
            configMapKeyRef:
              name: app2-config
              key: KAKAO_CLIENT_SECRET
        - name: KAKAO_AUTHORIZE_URL
          valueFrom:
            configMapKeyRef:
              name: app2-config
              key: KAKAO_AUTHORIZE_URL
        - name: KAKAO_TOKEN_URL
          valueFrom:
            configMapKeyRef:
              name: app2-config
              key: KAKAO_TOKEN_URL
        - name: KAKAO_API_BASE_URL
          valueFrom:
            configMapKeyRef:
              name: app2-config
              key: KAKAO_API_BASE_URL
        - name: KAKAO_REDIRECT_URI
          valueFrom:
            configMapKeyRef:
              name: app2-config
              key: KAKAO_REDIRECT_URI
        - name: KAKAO_USER_INFO_URL
          valueFrom:
            configMapKeyRef:
              name: app2-config
              key: KAKAO_USER_INFO_URL
        - name: KAKAO_USER_LOGOUT_URL
          valueFrom:
            configMapKeyRef:
              name: app2-config
              key: KAKAO_USER_LOGOUT_URL
        - name: DNS
          valueFrom:
            configMapKeyRef:
              name: app2-config
              key: DNS
        - name: SECURE
          valueFrom:
            configMapKeyRef:
              name: app2-config
              key: SECURE


      #   volumeMounts:
      #   - name: app2-env
      #     mountPath: "/etc/config"
      # volumes:
      # - name: app2-env
      #   configMap:
      #     name: app2-config

# 등록하기
# kubectl create -f app2-deployment.yaml

# 삭제하기
# kubectl delete -f app2-deployment.yaml

# 확인하기
# kubectl get deployments