apiVersion: v1
kind: ConfigMap

metadata:
  name: app3-config

data:
  ROOT_PATH: "/app2"

# 등록하기
# kubectl create -f app3-config.yaml

# 삭제하기
# kubectl delete -f app3-config.yaml

# 확인하기
# kubectl get configmaps