apiVersion: v1
kind: Pod

metadata:
  name: redis-pod
  labels:
    app: redis

spec:
  containers:
  - name: redis-container
    image: redis:8.4.0
    ports:
    - containerPort: 6379

# kubectl create -f redis-pod.yaml
# kubectl get pods