# 빌드하기 위해서 as build 입력
FROM node:24.13.0 as build

WORKDIR /app

COPY package.json ./

RUN npm i

COPY . .

RUN npm run build

FROM nginx:1.28

COPY --from=build /app/dist /usr/share/nginx/html
COPY ./default.conf /etc/nginx/conf.d/default.conf

EXPOSE 80

CMD ["nginx","-g","daemon off;"]

# 작성이 완료되면 아래 명령어 입력
# docker build -t react_3:0.1 .
# 이후 컨테이너 생성 및 실행
# docker run --network=my-net -d -p 80:80 --name app3 react_3:0.1